### Obtener todos los Personajes
GET http://localhost:4000/api/characters
Content-Type: application/json

### Obtener un Personaje específico por ID
GET http://localhost:4000/api/characters/66fd4df26a18917232e184f0


### Crear un nuevo Personaje
POST http://localhost:4000/api/characters/create-character
Content-Type: application/json

{
  "name": "Carlodasdsdta Wsing",
  "role": "Mago",
  "house": "Gryffindor",
  "alternate_names": [
    "Carlos",
    "Carlosa"
  ],
  "species": "Hombre",
  "wizard": true,
  "patronus": "El poder de la magia",
  "hogwartsStudent": true,
  "hogwartsStaff": true,
  "alive": true,
  "image": "https://i.pinimg.com/originals/b4/f5/c4/b4f5c4f9d5a6a1e6e3f4e8a8e7f7e4d.jpg"
}

### Registrar un nuevo emprendedor (Sign Up)
POST http://localhost:4000/api/entrepreneurs/signup
Content-Type: application/json

{
  "email": "n@n.com",
  "password": "123456",
  "firstName": "Carlos",
  "lastName": "López",
  "businessName": "Innovación Tech"
}

### Iniciar sesión (Log In)
POST http://localhost:4000/api/entrepreneurs/login
Content-Type: application/json

{
  "email": "zzs@zz.com",
  "password": "123456"
}

### Cerrar sesion
POST http://localhost:4000/api/entrepreneurs/logout
Content-Type: application/json


### Actualizar un emprendedor existente
PATCH http://localhost:4000/api/entrepreneurs/4
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jassssne.doe@example.com",
    "businessName": "Jane's Business",
    "products": [
        {
            "id": 20,
            "name": "Updadsted Product 20",
            "description": "Updated description for product 1",
            "price": 150
        }
    ]
}

### Eliminar un emprendedor
DELETE http://localhost:4000/api/entrepreneurs/2
Content-Type: application/json