### Obtener todos los Personajes
GET http://localhost:4000/api/characters
Content-Type: application/json

### Obtener un Personaje específico por ID
GET http://localhost:4000/api/characters/66fd469c1afe4728068549da


### Crear un nuevo Personaje
POST http://localhost:4000/api/characters/create-character
Content-Type: application/json

{
  "name": "Carlodasdsdta Wsing",
  "role": "Mago",
  "house": "Gryffindor",
  "alternate_names": [
    "Carlos",
    "Carlosa"
  ],
  "species": "Hombre",
  "wizard": true,
  "patronus": "El poder de la magia",
  "hogwartsStudent": true,
  "hogwartsStaff": true,
  "alive": true,
  "image": "https://i.pinimg.com/originals/b4/f5/c4/b4f5c4f9d5a6a1e6e3f4e8a8e7f7e4d.jpg"
}





### Eliminar un personaje
DELETE http://localhost:4000/api/characters/66fd61a059a19cc82e7ca5e7
Content-Type: application/json


### Actualizar un personaje existente
PUT http://localhost:4000/api/characters/66fd4de86a18917232e184ee
Content-Type: application/json

{
    "name": "Carlos Weasley",
    "role": "Mago",
    "house": "Gryffindor",
    "alternate_names": [
        "Carlos",
        "Carlosa"
    ],
    "species": "Hombre",
    "wizard": true,
    "patronus": "El poder de la magia",
    "hogwartsStudent": true,
    "hogwartsStaff": true,
    "alive": true,
    "image": "https://i.pinimg.com/originals/b4/f5/c4/b4f5c4f9d5a6a1e6e3f4e8a8e7f7e4d.jpg"
}